using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Comptatata.CodeAnalysis.JsonPolymorphic;

[Generator(LanguageNames.CSharp)]
public class MessageFileServerDispatcherGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var dispatcherClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax cds && 
                                            cds.Members.OfType<MethodDeclarationSyntax>()
                                                .Any(m => m.Identifier.Text == "DispatchAsync" && m.Modifiers.Any(mod => mod.IsKind(SyntaxKind.PartialKeyword))),
                transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            .Where(static m => m is not null);

        context.RegisterSourceOutput(dispatcherClasses.Collect().Combine(context.CompilationProvider),
            static (spc, source) => Execute(source.Right, source.Left, spc));
    }

    private static void Execute(Compilation compilation, ImmutableArray<ClassDeclarationSyntax> dispatcherClasses, SourceProductionContext context)
    {
        if (dispatcherClasses.IsDefaultOrEmpty) return;

        var commandSymbol = compilation.GetTypeByMetadataName("Comptatata.Communication.Messages.Command");
        var eventSymbol = compilation.GetTypeByMetadataName("Comptatata.Communication.Messages.Event");
        var serverBaseSymbol = compilation.GetTypeByMetadataName("Comptatata.Communication.CrossContainer.MessageFileDropServer");

        if (commandSymbol == null || eventSymbol == null || serverBaseSymbol == null) return;

        foreach (var dispatcherClass in dispatcherClasses.Distinct())
        {
            var semanticModel = compilation.GetSemanticModel(dispatcherClass.SyntaxTree);
            if (semanticModel.GetDeclaredSymbol(dispatcherClass) is not INamedTypeSymbol dispatcherSymbol)
                continue;

            var serverSymbol = dispatcherSymbol.Constructors
                .SelectMany(c => c.Parameters)
                .FirstOrDefault(p => IsAssignableTo(p.Type, serverBaseSymbol))?.Type as INamedTypeSymbol;

            if (serverSymbol == null) continue;

            // Find methods in serverSymbol that match the pattern
            var handlers = new List<IMethodSymbol>();
            foreach (var member in serverSymbol.GetMembers().OfType<IMethodSymbol>())
            {
                if (member.DeclaredAccessibility != Accessibility.Public || member.IsStatic) continue;
                if (member.Parameters.Length != 1) continue;

                var paramType = member.Parameters[0].Type;
                if (!IsAssignableTo(paramType, commandSymbol)) continue;

                var returnType = member.ReturnType as INamedTypeSymbol;
                if (returnType == null) continue;

                // Check if it's Task<T> or ValueTask<T>
                if (returnType.MetadataName != "Task`1" && returnType.MetadataName != "ValueTask`1") continue;
                
                var resultType = returnType.TypeArguments[0];
                if (!IsAssignableTo(resultType, eventSymbol)) continue;

                handlers.Add(member);
            }

            var source = GenerateDispatcherPartial(dispatcherSymbol, handlers);
            if (source != null)
            {
                var fileName = $"{dispatcherSymbol.ContainingNamespace}.{dispatcherSymbol.Name}.g.cs";
                context.AddSource(fileName, source);
            }
        }
    }

    private static string? GenerateDispatcherPartial(INamedTypeSymbol dispatcherSymbol, List<IMethodSymbol> handlers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Comptatata.Communication.Messages;");
        sb.AppendLine();
        sb.AppendLine($"namespace {dispatcherSymbol.ContainingNamespace};");
        sb.AppendLine();
        sb.AppendLine($"partial class {dispatcherSymbol.Name}");
        sb.AppendLine("{");

        // Internal DispatchAsync<TRequest, TResponse>
        sb.AppendLine("    internal partial async ValueTask<TResponse> DispatchAsync<TRequest, TResponse>(TRequest message)");
        sb.AppendLine("        where TRequest : Command where TResponse : Event");
        sb.AppendLine("    {");
        sb.AppendLine("        return (TResponse)await DispatchAsync((Command)message);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Non-generic DispatchAsync(Command message) for ReceiveAsync replacement
        sb.AppendLine("    internal async ValueTask<Event> DispatchAsync(Command message)");
        sb.AppendLine("    {");
        if (handlers.Count > 0)
        {
            sb.AppendLine("        return message switch");
            sb.AppendLine("        {");

            foreach (var handler in handlers)
            {
                var requestType = handler.Parameters[0].Type;
                sb.AppendLine($"            {requestType.ToDisplayString()} req => await _server.{handler.Name}(req),");
            }

            sb.AppendLine("            _ => new MethodNotFound(message.GetType().Name)");
            sb.AppendLine("        };");
        }
        else
        {
            sb.AppendLine("        return new MethodNotFound(message.GetType().Name);");
        }
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static bool IsAssignableTo(ITypeSymbol type, ITypeSymbol baseType)
    {
        var current = type;
        while (current != null)
        {
            if (SymbolEqualityComparer.Default.Equals(current, baseType))
                return true;
            current = current.BaseType;
        }
        return false;
    }
}
