using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Comptatata.CodeAnalysis.JsonPolymorphic;

[Generator(LanguageNames.CSharp)]
public class MessageFileServerDispatcherGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is InvocationExpressionSyntax ies &&
                                            ies.Expression is MemberAccessExpressionSyntax mes &&
                                            mes.Name is GenericNameSyntax gn &&
                                            gn.Identifier.Text == "AddHandler",
                transform: static (ctx, _) => GetHandlerType(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(handlerTypes.Collect().Combine(context.CompilationProvider),
            static (spc, source) => Execute(source.Right, source.Left!, spc));
    }

    private static ITypeSymbol? GetHandlerType(GeneratorSyntaxContext ctx)
    {
        var ies = (InvocationExpressionSyntax)ctx.Node;
        if (ies.Expression is not MemberAccessExpressionSyntax mes) return null;
        if (mes.Name is not GenericNameSyntax gn) return null;

        var typeArg = gn.TypeArgumentList.Arguments.FirstOrDefault();
        if (typeArg == null) return null;

        var typeInfo = ctx.SemanticModel.GetTypeInfo(typeArg);
        return typeInfo.Type;
    }

    private static void Execute(Compilation compilation, ImmutableArray<ITypeSymbol> handlerTypes, SourceProductionContext context)
    {
        if (handlerTypes.IsDefaultOrEmpty) return;

        var commandSymbol = compilation.GetTypeByMetadataName("Comptatata.Communication.Messages.Command");
        var eventSymbol = compilation.GetTypeByMetadataName("Comptatata.Communication.Messages.Event");
        var valueTaskSymbol = compilation.GetTypeByMetadataName("System.Threading.Tasks.ValueTask`1");

        if (commandSymbol == null || eventSymbol == null || valueTaskSymbol == null) return;

        var processedTypes = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);

        foreach (var handlerType in handlerTypes)
        {
            if (handlerType is not INamedTypeSymbol namedType || !processedTypes.Add(handlerType))
                continue;

            var methods = FindHandlerMethods(namedType, commandSymbol, eventSymbol, valueTaskSymbol);
            if (methods.Count == 0) continue;

            var source = GenerateDispatcher(namedType, methods);
            var fileName = $"{namedType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", "").Replace("<", "_").Replace(">", "_")}.Dispatcher.g.cs";
            context.AddSource(fileName, source);
        }
    }

    private static List<IMethodSymbol> FindHandlerMethods(INamedTypeSymbol type, INamedTypeSymbol commandSymbol, INamedTypeSymbol eventSymbol, INamedTypeSymbol valueTaskSymbol)
    {
        var methods = new List<IMethodSymbol>();
        foreach (var member in type.GetMembers().OfType<IMethodSymbol>())
        {
            if (member.DeclaredAccessibility != Accessibility.Public || member.IsStatic) continue;
            if (member.Parameters.Length != 1) continue;

            var paramType = member.Parameters[0].Type;
            if (!IsAssignableTo(paramType, commandSymbol)) continue;

            if (member.ReturnType is not INamedTypeSymbol returnType) continue;
            
            if (!SymbolEqualityComparer.Default.Equals(returnType.OriginalDefinition, valueTaskSymbol)) continue;

            var responseType = returnType.TypeArguments[0];
            if (!IsAssignableTo(responseType, eventSymbol)) continue;

            methods.Add(member);
        }
        return methods;
    }

    private static string GenerateDispatcher(INamedTypeSymbol handlerType, List<IMethodSymbol> methods)
    {
        var handlerFullName = handlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var dispatcherName = $"{handlerType.Name}Dispatcher";
        
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine("using Comptatata.Client.CrossContainer;");
        sb.AppendLine("using Comptatata.Communication.Messages;");
        sb.AppendLine();
        
        // We generate in a unique namespace to avoid collisions
        sb.AppendLine($"namespace Comptatata.Generated.Dispatchers;");
        sb.AppendLine();
        sb.AppendLine($"internal sealed class {dispatcherName}({handlerFullName} handler) : IMethodDispatcher");
        sb.AppendLine("{");
        sb.AppendLine($"    readonly {handlerFullName} _handler = handler;");
        sb.AppendLine();
        sb.AppendLine("    public async ValueTask<Event> DispatchAsync(Command command)");
        sb.AppendLine("    {");
        sb.AppendLine("        Event response = command switch");
        sb.AppendLine("        {");

        foreach (var method in methods)
        {
            var requestType = method.Parameters[0].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            {requestType} m => await _handler.{method.Name}(m).ConfigureAwait(false),");
        }

        sb.AppendLine("            _ => new MethodNotFound()");
        sb.AppendLine("        };");
        sb.AppendLine("        if (response is not MethodNotFound)");
        sb.AppendLine("        {");
        sb.AppendLine("            await MessageFileDrop.SendAsync(response).ConfigureAwait(false);");
        sb.AppendLine("        }");
        sb.AppendLine("        return response;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    [SuppressMessage(\"Usage\", \"CA2255: The 'ModuleInitializer' attribute should not be used in libraries\", Justification = \"Intentional auto-registration.\")]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine("    {");
        sb.AppendLine($"        DispatcherRegistry.RegisterDispatcher(\"{handlerFullName}\", new {dispatcherName}(new {handlerFullName}()));");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static bool IsAssignableTo(ITypeSymbol type, ITypeSymbol baseType)
    {
        var current = type;
        while (current != null)
        {
            if (SymbolEqualityComparer.Default.Equals(current, baseType))
                return true;
            current = current.BaseType;
        }
        return false;
    }
}
