using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Comptatata.CodeAnalysis.SpoolDrop;

[Generator(LanguageNames.CSharp)]
public class SpoolDropHandlerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsAddHandlerInvocation(s),
                transform: static (ctx, _) => GetHandlerType(ctx))
            .Where(static t => t is not null)
            .Select(static (t, _) => t!);

        context.RegisterSourceOutput(handlerTypes.Collect().Combine(context.CompilationProvider), 
            static (spc, source) => Execute(source.Left, spc));
    }

    private static bool IsAddHandlerInvocation(SyntaxNode node)
    {
        return node is InvocationExpressionSyntax invocation &&
               (invocation.Expression is MemberAccessExpressionSyntax memberAccess && memberAccess.Name.Identifier.Text == "AddHandler" ||
                invocation.Expression is IdentifierNameSyntax identifier && identifier.Identifier.Text == "AddHandler");
    }

    private static ITypeSymbol? GetHandlerType(GeneratorSyntaxContext context)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;
        var symbol = context.SemanticModel.GetSymbolInfo(invocation).Symbol as IMethodSymbol;

        if (symbol is null || symbol.Name != "AddHandler") return null;

        var containingType = symbol.ContainingType?.ToDisplayString();
        if (containingType != "Comptatata.MessageDrop.SpoolDropServer") return null;

        return symbol.TypeArguments.FirstOrDefault();
    }

    private static void Execute(ImmutableArray<ITypeSymbol> handlers, SourceProductionContext context)
    {
        var distinctHandlers = handlers.Distinct(SymbolEqualityComparer.Default).Cast<INamedTypeSymbol>();

        foreach (var handler in distinctHandlers)
        {
            GenerateSerializerContext(handler, context);
        }
    }

    private static void GenerateSerializerContext(INamedTypeSymbol handler, SourceProductionContext context)
    {
        var methods = handler.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m => m.MethodKind == MethodKind.Ordinary && m.DeclaredAccessibility == Accessibility.Public && !m.IsStatic)
            .ToList();

        var messageTypes = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);
        foreach (var method in methods)
        {
            if (method.Parameters.Length != 1) continue;

            if (method.ReturnType is INamedTypeSymbol returnType &&
                returnType.Name == "ValueTask" &&
                returnType.ContainingNamespace.ToDisplayString() == "System.Threading.Tasks" &&
                returnType.TypeArguments.Length == 1)
            {
                messageTypes.Add(returnType.TypeArguments[0]);
                messageTypes.Add(method.Parameters[0].Type);
            }
        }

        if (messageTypes.Count == 0) return;

        var handlerName = handler.Name;
        var fullHandlerName = handler.ToDisplayString();
        var hash = GetStableHash(fullHandlerName);
        var ns = handler.ContainingNamespace.IsGlobalNamespace ? "" : handler.ContainingNamespace.ToDisplayString();
        
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }
        
        foreach (var messageType in messageTypes.OrderBy(t => t.ToDisplayString()))
        {
            sb.AppendLine($"[JsonSerializable(typeof({messageType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}))]");
        }
        sb.AppendLine($"internal partial class {handlerName}_{hash} : JsonSerializerContext");
        sb.AppendLine("{");
        sb.AppendLine("}");

        var syntaxRef = handler.DeclaringSyntaxReferences.FirstOrDefault();
        if (syntaxRef != null)
        {
            var sourcePath = syntaxRef.SyntaxTree.FilePath;
            if (!string.IsNullOrEmpty(sourcePath))
            {
                var directory = Path.GetDirectoryName(sourcePath);
                if (directory != null)
                {
                    var fileName = $"{handlerName}_{hash}.cs";
                    var outputPath = Path.Combine(directory, fileName);
                    var newContent = sb.ToString();

                    if (!File.Exists(outputPath) || File.ReadAllText(outputPath) != newContent)
                    {
                        File.WriteAllText(outputPath, newContent);
                    }
                }
            }
        }
    }

    private static string GetStableHash(string str)
    {
        uint hash = 0;
        foreach (char c in str)
        {
            hash = hash * 31 + c;
        }
        return hash.ToString("X8");
    }
}
