using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Comptatata.CodeAnalysis.SpoolDrop;

[Generator(LanguageNames.CSharp)]
public class SpoolDropHandlerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsAddHandlerInvocation(s),
                transform: static (ctx, _) => GetHandlerType(ctx))
            .Where(static t => t is not null)
            .Select(static (t, _) => t!);

        context.RegisterSourceOutput(handlerTypes.Collect().Combine(context.CompilationProvider), 
            static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static bool IsAddHandlerInvocation(SyntaxNode node)
    {
        return node is InvocationExpressionSyntax invocation &&
               (invocation.Expression is MemberAccessExpressionSyntax memberAccess && memberAccess.Name.Identifier.Text == "AddHandler" ||
                invocation.Expression is IdentifierNameSyntax identifier && identifier.Identifier.Text == "AddHandler");
    }

    private static ITypeSymbol? GetHandlerType(GeneratorSyntaxContext context)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;
        var symbol = context.SemanticModel.GetSymbolInfo(invocation).Symbol as IMethodSymbol;

        if (symbol is null || symbol.Name != "AddHandler") return null;

        var containingType = symbol.ContainingType?.ToDisplayString();
        if (containingType != "Comptatata.MessageDrop.SpoolDropServer") return null;

        return symbol.TypeArguments.FirstOrDefault();
    }

    private class HandlerMethodInfo
    {
        public HandlerMethodInfo(IMethodSymbol method, ITypeSymbol parameterType, ITypeSymbol returnType, bool isAsync)
        {
            Method = method;
            ParameterType = parameterType;
            ReturnType = returnType;
            IsAsync = isAsync;
        }

        public IMethodSymbol Method { get; }
        public ITypeSymbol ParameterType { get; }
        public ITypeSymbol ReturnType { get; }
        public bool IsAsync { get; }
    }

    private static void Execute(ImmutableArray<ITypeSymbol> handlers, Compilation compilation, SourceProductionContext context)
    {
        var distinctHandlers = handlers.Distinct(SymbolEqualityComparer.Default).Cast<INamedTypeSymbol>();

        var groupedByFile = distinctHandlers.GroupBy(h => h.DeclaringSyntaxReferences.FirstOrDefault()?.SyntaxTree.FilePath)
            .Where(g => !string.IsNullOrEmpty(g.Key));

        foreach (var group in groupedByFile)
        {
            GenerateFileForGroup(group.Key!, group.ToList(), compilation, context);
        }
    }

    private static void GenerateFileForGroup(string sourcePath, List<INamedTypeSymbol> handlers, Compilation compilation, SourceProductionContext context)
    {
        var directory = Path.GetDirectoryName(sourcePath);
        if (directory == null) return;

        var sourceFileName = Path.GetFileNameWithoutExtension(sourcePath);
        var outputPath = Path.Combine(directory, $"{sourceFileName}.generated.cs");

        // Cleanup old per-handler files
        foreach (var handler in handlers)
        {
            var oldPath = Path.Combine(directory, $"{sourceFileName}.{handler.Name}.generated.cs");
            if (File.Exists(oldPath))
            {
                try { File.Delete(oldPath); } catch { }
            }
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using System.Text.Json.Serialization.Metadata;");
        sb.AppendLine("using Comptatata.MessageDrop;");
        sb.AppendLine();

        // Assume same namespace for now as it's the 99% case for file-scoped namespaces
        var firstHandler = handlers.First();
        var ns = firstHandler.ContainingNamespace.IsGlobalNamespace ? "" : firstHandler.ContainingNamespace.ToDisplayString();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        foreach (var handler in handlers)
        {
            var handlerInfo = GetHandlerInfo(handler, compilation);
            if (handlerInfo.Methods.Count == 0) continue;

            foreach (var messageType in handlerInfo.MessageTypes.OrderBy(t => t.ToDisplayString()))
            {
                sb.AppendLine($"[JsonSerializable(typeof({messageType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}))]");
            }
            sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
            sb.AppendLine($"public partial class {handler.Name}SpoolBusSerializer : JsonSerializerContext");
            sb.AppendLine("{");
            sb.AppendLine("    public static JsonSerializerOptions SpoolBusOptions => field ??= ConstructPolymorphism();");
            sb.AppendLine();
            sb.AppendLine("    private static JsonSerializerOptions ConstructPolymorphism()");
            sb.AppendLine("    {");
            sb.AppendLine("        var options = new JsonSerializerOptions();");
            sb.AppendLine("        options.TypeInfoResolver = JsonTypeInfoResolver.WithAddedModifier(Default, AddPolymorphism);");
            sb.AppendLine("        return options;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    private static void AddPolymorphism(JsonTypeInfo typeInfo)");
            sb.AppendLine("    {");
            sb.AppendLine("        typeInfo.PolymorphismOptions = typeInfo switch");
            sb.AppendLine("        {");

            var abstractTypes = handlerInfo.MessageTypes.Where(t => t.IsAbstract).ToList();
            foreach (var parent in abstractTypes.OrderBy(t => t.ToDisplayString()))
            {
                var concreteDescendants = handlerInfo.MessageTypes
                    .Where(t => !t.IsAbstract && IsDescendantOf(t, parent))
                    .OrderBy(t => t.Name)
                    .ToList();

                if (concreteDescendants.Count > 0)
                {
                    sb.Append($"            JsonTypeInfo<{parent.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}> => SpoolBusPolymorphism.Options");
                    foreach (var descendant in concreteDescendants)
                    {
                        var discriminator = ToKebabCase(descendant.Name);
                        sb.AppendLine();
                        sb.Append($"                .AddDerived<{descendant.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(\"{discriminator}\")");
                    }
                    sb.AppendLine(",");
                }
            }

            sb.AppendLine("            _ => typeInfo.PolymorphismOptions");
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();

            // Generate Dispatcher
            sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
            sb.AppendLine($"public static class {handler.Name}SpoolBusDispatcher");
            sb.AppendLine("{");
            sb.AppendLine($"    public static async global::System.Threading.Tasks.ValueTask<global::Comptatata.MessageDrop.Messages.Message?> DispatchAsync(");
            sb.AppendLine($"        {handler.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} handler,");
            sb.AppendLine($"        byte[] buffer)");
            sb.AppendLine("    {");
            sb.AppendLine($"        var message = global::System.Text.Json.JsonSerializer.Deserialize<global::Comptatata.MessageDrop.Messages.Message>(buffer, {handler.Name}SpoolBusSerializer.SpoolBusOptions);");
            sb.AppendLine("        return message switch");
            sb.AppendLine("        {");

            foreach (var method in handlerInfo.Methods)
            {
                var awaitPrefix = method.IsAsync ? "await " : "";
                sb.AppendLine($"            {method.ParameterType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} m => {awaitPrefix}handler.{method.Method.Name}(m),");
            }

            sb.AppendLine("            _ => null");
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();

            // Generate Infrastructure Initializer
            sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
            sb.AppendLine($"internal static class {handler.Name}SpoolBusInfrastructureInitializer");
            sb.AppendLine("{");
            sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
            sb.AppendLine("    public static void Initialize()");
            sb.AppendLine("    {");
            sb.AppendLine($"        global::Comptatata.MessageDrop.SpoolBusInfrastructure<{handler.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>.Options = {handler.Name}SpoolBusSerializer.SpoolBusOptions;");
            sb.AppendLine($"        global::Comptatata.MessageDrop.SpoolBusInfrastructure<{handler.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>.Dispatcher = {handler.Name}SpoolBusDispatcher.DispatchAsync;");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        var newContent = sb.ToString();
        if (!File.Exists(outputPath) || File.ReadAllText(outputPath) != newContent)
        {
            File.WriteAllText(outputPath, newContent);
        }
    }

    private static bool IsDescendantOf(ITypeSymbol type, ITypeSymbol potentialBase)
    {
        var targetBase = potentialBase.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var current = type.BaseType;
        while (current != null)
        {
            if (current.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == targetBase) return true;
            current = current.BaseType;
        }
        return false;
    }

    private static string ToKebabCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        var sb = new StringBuilder();
        for (int i = 0; i < name.Length; i++)
        {
            char c = name[i];
            if (char.IsUpper(c))
            {
                if (i > 0) sb.Append('-');
                sb.Append(char.ToLower(c));
            }
            else
            {
                sb.Append(c);
            }
        }
        return sb.ToString();
    }

    private class HandlerInfo
    {
        public HandlerInfo(HashSet<ITypeSymbol> messageTypes, List<HandlerMethodInfo> methods)
        {
            MessageTypes = messageTypes;
            Methods = methods;
        }

        public HashSet<ITypeSymbol> MessageTypes { get; }
        public List<HandlerMethodInfo> Methods { get; }
    }

    private static HandlerInfo GetHandlerInfo(INamedTypeSymbol handler, Compilation compilation)
    {
        var messageTypes = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);

        // Find all type references in the handler's syntax
        foreach (var syntaxRef in handler.DeclaringSyntaxReferences)
        {
            var model = compilation.GetSemanticModel(syntaxRef.SyntaxTree);
            var root = syntaxRef.GetSyntax();

            var nodes = root.DescendantNodesAndSelf();
            foreach (var node in nodes)
            {
                ITypeSymbol? symbol = null;
                if (node is TypeSyntax typeSyntax)
                {
                    symbol = model.GetSymbolInfo(typeSyntax).Symbol as ITypeSymbol;
                }
                else if (node is ObjectCreationExpressionSyntax creation)
                {
                    symbol = model.GetSymbolInfo(creation).Symbol?.ContainingType as ITypeSymbol ?? model.GetTypeInfo(creation).Type;
                }
                else if (node is VariableDeclaratorSyntax declarator)
                {
                    // Handle var x = new MyEvent();
                    var variableSymbol = model.GetDeclaredSymbol(declarator) as ILocalSymbol;
                    symbol = variableSymbol?.Type;
                }

                if (symbol != null && IsOrInheritsFromMessage(symbol))
                {
                    AddWithHierarchy(messageTypes, symbol);
                }
            }
        }

        var methods = handler.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m => m.MethodKind == MethodKind.Ordinary && m.DeclaredAccessibility == Accessibility.Public && !m.IsStatic)
            .ToList();

        var handlerMethods = new List<HandlerMethodInfo>();

        foreach (var method in methods)
        {
            if (method.Parameters.Length != 1) continue;

            ITypeSymbol? messageResultType = null;
            bool isAsync = false;

            var returnType = method.ReturnType as INamedTypeSymbol;
            if (returnType != null && returnType.IsGenericType)
            {
                var fullName = returnType.ConstructedFrom.ToDisplayString();
                if (fullName == "System.Threading.Tasks.ValueTask<TResult>" ||
                    fullName == "System.Threading.Tasks.Task<TResult>" ||
                    fullName == "System.Threading.Tasks.ValueTask<T>" ||
                    fullName == "System.Threading.Tasks.Task<T>")
                {
                    messageResultType = returnType.TypeArguments[0];
                    isAsync = true;
                }
            }

            if (messageResultType == null)
            {
                messageResultType = method.ReturnType;
                isAsync = false;
            }

            if (messageResultType != null && IsOrInheritsFromMessage(messageResultType))
            {
                var paramType = method.Parameters[0].Type;
                if (IsOrInheritsFromMessage(paramType))
                {
                    handlerMethods.Add(new HandlerMethodInfo(method, paramType, messageResultType, isAsync));
                    AddWithHierarchy(messageTypes, messageResultType);
                    AddWithHierarchy(messageTypes, paramType);
                }
            }
        }
        return new HandlerInfo(messageTypes, handlerMethods);
    }

    private static bool IsOrInheritsFromMessage(ITypeSymbol type)
    {
        var current = type;
        while (current != null)
        {
            if (current.Name == "Message" && current.ContainingNamespace?.ToDisplayString() == "Comptatata.MessageDrop.Messages") return true;
            current = current.BaseType;
        }
        return false;
    }

    private static void AddWithHierarchy(HashSet<ITypeSymbol> types, ITypeSymbol type)
    {
        var current = type;
        while (current != null && current.SpecialType != SpecialType.System_Object)
        {
            types.Add(current);
            current = current.BaseType;
        }
    }
}
