using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Comptatata.CodeAnalysis.SpoolDrop;

[Generator(LanguageNames.CSharp)]
public class SpoolDropHandlerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsAddHandlerInvocation(s),
                transform: static (ctx, _) => GetHandlerType(ctx))
            .Where(static t => t is not null)
            .Select(static (t, _) => t!);

        context.RegisterSourceOutput(handlerTypes.Collect().Combine(context.CompilationProvider), 
            static (spc, source) => Execute(source.Left, spc));
    }

    private static bool IsAddHandlerInvocation(SyntaxNode node)
    {
        return node is InvocationExpressionSyntax invocation &&
               (invocation.Expression is MemberAccessExpressionSyntax memberAccess && memberAccess.Name.Identifier.Text == "AddHandler" ||
                invocation.Expression is IdentifierNameSyntax identifier && identifier.Identifier.Text == "AddHandler");
    }

    private static ITypeSymbol? GetHandlerType(GeneratorSyntaxContext context)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;
        var symbol = context.SemanticModel.GetSymbolInfo(invocation).Symbol as IMethodSymbol;

        if (symbol is null || symbol.Name != "AddHandler") return null;

        var containingType = symbol.ContainingType?.ToDisplayString();
        if (containingType != "Comptatata.MessageDrop.SpoolDropServer") return null;

        return symbol.TypeArguments.FirstOrDefault();
    }

    private static void Execute(ImmutableArray<ITypeSymbol> handlers, SourceProductionContext context)
    {
        var distinctHandlers = handlers.Distinct(SymbolEqualityComparer.Default).Cast<INamedTypeSymbol>();

        var groupedByFile = distinctHandlers.GroupBy(h => h.DeclaringSyntaxReferences.FirstOrDefault()?.SyntaxTree.FilePath)
            .Where(g => !string.IsNullOrEmpty(g.Key));

        foreach (var group in groupedByFile)
        {
            GenerateFileForSourceFile(group.Key!, group, context);
        }
    }

    private static void GenerateFileForSourceFile(string sourcePath, IEnumerable<INamedTypeSymbol> handlers, SourceProductionContext context)
    {
        var directory = Path.GetDirectoryName(sourcePath);
        if (directory == null) return;

        var sourceFileName = Path.GetFileNameWithoutExtension(sourcePath);
        var outputPath = Path.Combine(directory, $"{sourceFileName}.generated.cs");

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using System.Text.Json.Serialization.Metadata;");
        sb.AppendLine("using Comptatata.MessageDrop;");
        sb.AppendLine();

        var byNamespace = handlers.GroupBy(h => h.ContainingNamespace.IsGlobalNamespace ? "" : h.ContainingNamespace.ToDisplayString()).ToList();

        foreach (var nsGroup in byNamespace)
        {
            var ns = nsGroup.Key;
            bool useBlock = byNamespace.Count > 1;

            if (!string.IsNullOrEmpty(ns))
            {
                if (useBlock)
                {
                    sb.AppendLine($"namespace {ns}");
                    sb.AppendLine("{");
                }
                else
                {
                    sb.AppendLine($"namespace {ns};");
                    sb.AppendLine();
                }
            }

            var indent = useBlock ? "    " : "";
            foreach (var handler in nsGroup)
            {
                var messageTypes = GetMessageTypes(handler);
                if (messageTypes.Count == 0) continue;

                foreach (var messageType in messageTypes.OrderBy(t => t.ToDisplayString()))
                {
                    sb.AppendLine($"{indent}[JsonSerializable(typeof({messageType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}))]");
                }
                sb.AppendLine($"{indent}internal partial class {handler.Name}SpoolBusSerializer : JsonSerializerContext");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    public static JsonSerializerOptions SpoolBusOptions => field ??= ConstructPolymorphism();");
                sb.AppendLine();
                sb.AppendLine($"{indent}    private static JsonSerializerOptions ConstructPolymorphism()");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        var options = new JsonSerializerOptions();");
                sb.AppendLine($"{indent}        options.TypeInfoResolver = JsonTypeInfoResolver.WithAddedModifier(Default, AddPolymorphism);");
                sb.AppendLine($"{indent}        return options;");
                sb.AppendLine($"{indent}    }}");
                sb.AppendLine();
                sb.AppendLine($"{indent}    private static void AddPolymorphism(JsonTypeInfo typeInfo)");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        typeInfo.PolymorphismOptions = typeInfo switch");
                sb.AppendLine($"{indent}        {{");

                var abstractTypes = messageTypes.Where(t => t.IsAbstract).ToList();
                foreach (var parent in abstractTypes.OrderBy(t => t.ToDisplayString()))
                {
                    var concreteDescendants = messageTypes
                        .Where(t => !t.IsAbstract && IsDescendantOf(t, parent))
                        .OrderBy(t => t.Name)
                        .ToList();

                    if (concreteDescendants.Count > 0)
                    {
                        sb.Append($"{indent}            JsonTypeInfo<{parent.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}> => SpoolBusPolymorphism.Options");
                        foreach (var descendant in concreteDescendants)
                        {
                            var discriminator = ToKebabCase(descendant.Name);
                            sb.AppendLine();
                            sb.Append($"{indent}                .AddDerived<{descendant.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(\"{discriminator}\")");
                        }
                        sb.AppendLine(",");
                    }
                }

                sb.AppendLine($"{indent}            _ => typeInfo.PolymorphismOptions");
                sb.AppendLine($"{indent}        }};");
                sb.AppendLine($"{indent}    }}");
                sb.AppendLine($"{indent}}}");
                sb.AppendLine();
            }

            if (useBlock && !string.IsNullOrEmpty(ns))
            {
                sb.AppendLine("}");
            }
        }

        var newContent = sb.ToString();
        if (!File.Exists(outputPath) || File.ReadAllText(outputPath) != newContent)
        {
            File.WriteAllText(outputPath, newContent);
        }
    }

    private static bool IsDescendantOf(ITypeSymbol type, ITypeSymbol potentialBase)
    {
        var current = type.BaseType;
        while (current != null && current.SpecialType != SpecialType.System_Object)
        {
            if (SymbolEqualityComparer.Default.Equals(current, potentialBase)) return true;
            current = current.BaseType;
        }
        return false;
    }

    private static string ToKebabCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        var sb = new StringBuilder();
        for (int i = 0; i < name.Length; i++)
        {
            char c = name[i];
            if (char.IsUpper(c))
            {
                if (i > 0) sb.Append('-');
                sb.Append(char.ToLower(c));
            }
            else
            {
                sb.Append(c);
            }
        }
        return sb.ToString();
    }

    private static HashSet<ITypeSymbol> GetMessageTypes(INamedTypeSymbol handler)
    {
        var methods = handler.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m => m.MethodKind == MethodKind.Ordinary && m.DeclaredAccessibility == Accessibility.Public && !m.IsStatic)
            .ToList();

        var messageTypes = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);
        foreach (var method in methods)
        {
            if (method.Parameters.Length != 1) continue;

            if (method.ReturnType is INamedTypeSymbol returnType &&
                returnType.Name == "ValueTask" &&
                returnType.ContainingNamespace.ToDisplayString() == "System.Threading.Tasks" &&
                returnType.TypeArguments.Length == 1)
            {
                AddWithHierarchy(messageTypes, returnType.TypeArguments[0]);
                AddWithHierarchy(messageTypes, method.Parameters[0].Type);
            }
        }
        return messageTypes;
    }

    private static void AddWithHierarchy(HashSet<ITypeSymbol> types, ITypeSymbol type)
    {
        var current = type;
        while (current != null && current.SpecialType != SpecialType.System_Object)
        {
            types.Add(current);
            current = current.BaseType;
        }
    }
}
